compute_environment: LOCAL_MACHINE
debug: true
distributed_type: MULTI_GPU
dynamo_backend: 'NO'
gpu_ids: all
machine_rank: 0
main_process_ip: 172.16.0.105
main_process_port: 12345
main_training_function: main
megatron_lm_config: {}
mixed_precision: bf16
num_machines: 7
num_processes: 18
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
